name:                mte544
version:             0.1.0.0
github:              "jwang61/MTE544Assignment"
license:             BSD3
author:              "Justin Wang"
maintainer:          "example@example.com"
copyright:           "2020 Justin Wang"

extra-source-files:
- README.md

description:         mte544

dependencies:
- base >= 4.7 && < 5
- linear
- mtl
- lens
- normaldistribution
- easyplot

library:
  source-dirs: src

executables:
  mte544-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mte544
